### ISSUE TITLE
Align create form journey with with prototype

### ISSUE THREAD

**Issue by DavidBiddle** [alphagov/forms-admin#74]
## Tasks
- [ ] Use a [Start button](https://design-system.service.gov.uk/components/button/#start-buttons) for the create a form button on the homepage, instead of a normal button
- [ ] Make the label for the respective form name and email pages use h1 elements
- [ ] Separate the email address question from the form name question, and don't include it in the create a form journey
- [ ] Make the form name and email pages 2/3 width
- [ ] Set the submission email to an empty string when the form is created

## Trello cards:
https://trello.com/c/DzXscuZj/426-landing-page-forms-as-a-start-button
https://trello.com/c/0PVwvL3k/427-create-a-form-journey-update
